apiVersion: batch/v1
kind: Job
metadata:
  name: cyb-sub
spec:
  parallelism: ${COUNT}
  template:
    metadata:
      name: cyb-sub
      labels:
        app: cyb
    spec:
      containers:
      - name: subscriber
        image: avish1990/subscriber:1.0
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /var/secrets/google
          readOnly: true

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        - name: PARALLEL_COUNT
          valueFrom:
            secretKeyRef:
              name: k8-count
              key: COUNT

      restartPolicy: OnFailure
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
