apiVersion: batch/v1
kind: Job
metadata:
  name: cyb-sub
spec:
  parallelism: 15
  template:
    metadata:
      name: cyb-sub
      labels:
        app: cyb
    spec:
      containers:
      - name: subscriber
        image: avish1990/subscriber:2.0
        command: ["python", "-u", "/subscriber/subscriber.py"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /var/secrets/google
          readOnly: true

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        - name: PROJECT
          valueFrom:
            secretKeyRef:
              name: gcp-project-id
              key: PROJECT

      restartPolicy: OnFailure
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
