apiVersion: batch/v1
kind: Job
metadata:
  name: cyb-process
spec:
  parallelism: 5
  template:
    metadata:
      name: cyb-process
      labels:
        app: cyb
    spec:
      containers:
      - name: cybqueuereceiver
        image: avish1990/subscriber:1.0
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
      restartPolicy: OnFailure
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
