apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyb-cron
  labels:
    app: cyb-cron
spec:
      selector:
        matchLabels:
          app: cyb-cron
      strategy:
        type: Recreate
      replicas: 1
      template:
        metadata:
          labels:
            app: cyb-cron
        spec:
          containers:
          - name: scheduler
            image: avish1990/scheduler:1.0
            imagePullPolicy: Always
            volumeMounts:
            - name: kube-cluster-config
              mountPath: /cluster-config

            - name: invoker-config
              mountPath: /invoker-config
            - name: subscriber-config
              mountPath: /subscriber-config
        
            - name: cloudsql-instance-credentials
              mountPath: /var/secrets/google
              readOnly: true

            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/credentials.json

          volumes:
          - name: kube-cluster-config
            configMap:
              name: kube-config
          - name: invoker-config
            configMap:
              name: invoker-config
          - name: subscriber-config
            configMap:
              name: subscriber-config
          - name: cloudsql-instance-credentials
            secret:
              secretName: cloudsql-instance-credentials


